#!/bin/bash
# backup script

#getting the current directory
BASEDIR=$(dirname $0);
TODAY=`date +%Y-%m-%d`;
BACKUP_FOLER=$BASEDIR/$TODAY;

usage(){
	echo "Usage: $0 HTML_ROOT_PATH "
	exit 1
}

#function to create a tmp backup folder
createBackupFile() {
	local backup_folder=$1;
	if [ ! -d $backup_folder ] ; then
		mkdir $backup_folder;	
	fi
	return 0;
}

#creating a backup folder
createBackupFile $BACKUP_FOLER;
